name: webf_websocket
description: WebSocket API support for webf apps.
version: 1.1.0
homepage: https://openwebf.com
repository: https://github.com/openwebf/plugins
environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.2.0
  webf: 
    git: 
      url: git@github.com:wittech/webf.git
      ref: main
      path: webf

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
